<?xml version="1.0" ?>
<robot name="caato2" xmlns:xacro="https://www.ros.org/wiki/xacro" >
	<xacro:arg name="botname" default=""/>

  <!-- Base Properties (Estimated) -->
  <xacro:property name="base_width" value="0.54" />
  <xacro:property name="base_depth" value="0.52" />
  <xacro:property name="base_height" value="0.37" />
  <xacro:property name="base_mass" value="46.143" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="NA since differential drive" />
  <xacro:property name="track" value="0.470" />
  <xacro:property name="wheel_vertical_offset" value="0.0518" /> 

  <!-- Wheel Properties -->
  <xacro:property name="wheel_width" value="0.05" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_mass" value="1.2" />


  <!-- Caster Wheel Properties -->
  <xacro:property name="caster_wheel_width" value="0.035" />
  <xacro:property name="caster_wheel_radius" value="0.05" />
  <xacro:property name="caster_wheel_mass" value="0.8" />

  <!-- Included URDF or XACRO Files -->
  <xacro:include filename="$(find caato2_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find caato2_description)/urdf/accessories/caato2.gazebo.xacro"/>

	<!-- Macro for calculating inertias -->
	<xacro:macro name="cylinder_inertia" params="m r h">
		<inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
				iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
				izz="${m*r*r/2}" /> 
	</xacro:macro>

    <xacro:macro name="cuboid_inertia" params="m w h d">
        <inertia ixx="${m*(h*h+d*d)/12}" ixy = "0" ixz = "0"
                iyy="${m*(w*w+d*d)/12}" iyz = "0"
                izz="${m*(w*w+h*h)/12}" /> 
    </xacro:macro>

  <link name="base_footprint">
    <origin rpy="0 0 0" xyz="0 0 0"/> 
  </link>

  <joint name="base_joint" type="fixed">
  <!-- Rotated to match rviz config -->
    <origin xyz="-0.0 0 ${wheel_radius}" rpy="0 0 ${pi/2}"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <dynamics damping="0" friction="0"/>
  </joint>

  <!-- Base link origin is at the centre of rotation of differential drive robot -->
  <link name="base_link">
    <collision name="collision_chassis">
      <origin rpy="0 0 0" xyz="0.08 0.172 0.182"/>  
      <geometry>
        <mesh filename="package://caato2_description/meshes/bases/body_with_arm.stl"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0.08 0.172 0.182"/>  
      <geometry>
        <mesh filename="package://caato2_description/meshes/bases/body_with_arm.stl"/>
      </geometry>
      <material name="yellow"/>
    </visual>

  	<!-- Left Caster Wheel Visual -->
     <collision name="left_caster_wheel_collision">
      <origin xyz="0.184979 -0.22 -0.0516" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="left_caster_wheel_visual">
      <origin xyz="0.184979 -0.22 0.0484" rpy="0 0 1.2"/>
      <geometry>
        <mesh filename="package://caato2_description/meshes/wheels/caster_wheel.stl"/>
      </geometry>
    </visual>

    <!-- Right Caster Wheel Visual -->
    <collision name="right_caster_wheel_collision">
    <origin xyz="-0.184979 -0.22 -0.0516" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="right_caster_wheel_visual">
      <origin xyz="-0.184979 -0.22 0.0484" rpy="0 0 1.2"/>
      <geometry>
        <mesh filename="package://caato2_description/meshes/wheels/caster_wheel.stl"/>
      </geometry>
    </visual>

  </link>

  <gazebo reference="base_link">
    <kp>10000000</kp>
    <kd>1.0</kd>
    <material>Gazebo/Blue</material>
    <mu1 value ="0"/>
    <mu2 value ="0"/>
    <minDepth>0.001</minDepth>
</gazebo>

  <!-- In case of IMU -->
  <link name="imu_link">
    <origin rpy="0 0 0" xyz="0 0 0"/> 
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- for the sake of a box body, original stl blocking lidars -->

  <link name="body_link">
    <origin rpy="0 0 0" xyz="0 0 0"/> 
  </link>

  <joint name="body_joint" type="fixed">
    <parent link="base_link"/>
    <child link="body_link"/>
    <origin xyz="0 -0.05 0.14" rpy="0 0 0"/>
  </joint>


  <link name="inertial_link" >
    <inertial>
      <mass value="${base_mass}" />
      <!--shifted weight if needed to prevent jerking-->
      <origin xyz="0 0 -0.13"/>
      <xacro:cuboid_inertia m="${base_mass}" w="${base_width}" h="${base_height}" d="${base_depth}"/>
    </inertial> 
  </link>

  <joint name="inertial_joint" type="fixed" >
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>


  	<!-- Right Wheel -->
  <link name="right_wheel_link">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}" />
    </inertial>
    <collision name="right_wheel_collision">
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="package://caato2_description/meshes/wheels/Wheel.stl"/>
      </geometry>
    </visual>
  </link>
				
  <joint name="right_wheel_joint" type="continuous">
    <origin rpy="0 0 0" xyz="${-track/2} 0 0"/>
    <child link="right_wheel_link"/>
    <parent link="base_link"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="0" friction="1.0"/>
  </joint>

  <!-- Left Wheel -->
  <link name="left_wheel_link">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 ${-pi/2}"/>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}" />
    </inertial>
    <collision name="left_wheel_collision">
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${pi/2}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="${pi} 0 ${pi/2}"/>
      <geometry>
        <mesh filename="package://caato2_description/meshes/wheels/Wheel.stl"/>
      </geometry>
    </visual>
  </link>
				
  <joint name="left_wheel_joint" type="continuous">
    <origin rpy="0 0 0" xyz="${track/2} 0 0"/>
    <child link="left_wheel_link"/>
    <parent link="base_link"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="0" friction="1.0"/>
  </joint>

  <!-- Lider Sensor 1_Front -->
  <link name="hokuyo_laser_scanner_1">
    <visual>
      <origin xyz="0 0 -0.06" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://caato2_description/meshes/sensors/hokuyo_laser_scanner.stl"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 -0.06" rpy="0 0 3.93"/>
      <mass value="0.2" />
      <inertia ixx="0" ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link>

	<joint name="hokuyo_laser_scanner_1_joint" type="fixed">
		<origin xyz="-0.210233 -0.262308 0.203200" rpy="0 0 3.93" />
		<parent link="base_link" />
		<child link="hokuyo_laser_scanner_1" />
		<axis xyz="0 0 1"/>
	</joint>

  <!-- Lider Sensor 2_Back -->
  <link name="hokuyo_laser_scanner_2">
    <visual>
      <origin xyz="0 0 -0.06" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://caato2_description/meshes/sensors/hokuyo_laser_scanner.stl"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 -0.06" rpy="0 0 0.785"/>
      <mass value="0.2" />
      <inertia ixx="0" ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link>

	<joint name="hokuyo_laser_scanner_2_joint" type="fixed">
		<origin xyz="0.213805 0.115872 0.203200" rpy="0 0 0.785" />
		<parent link="base_link" />
		<child link="hokuyo_laser_scanner_2" />
		<axis xyz="0 0 1"/>
	</joint>

  <!-- front realsense sensor -->
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.2.front.urdf.xacro"/>
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.front.gazebo.xacro"/>
  <xacro:d435_front parent="base_link">
      <origin xyz="-0 -0.34 0.35" rpy="0 0 -1.57" />
  </xacro:d435_front> 

  <!-- back realsense sensor -->
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.2.urdf.xacro"/>
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.gazebo.xacro"/>
  <xacro:sensor_d435 parent="base_link">
      <origin xyz="0 0.28 0.46" rpy="0 0 1.57" />
  </xacro:sensor_d435>   
  
</robot>
