<?xml version="1.0"?>
<robot name="caato2_gazebo" xmlns:xacro="http://ros.org/wiki/xacro">

  <gazebo>
    <plugin name="caato2_controller" filename="libgazebo_ros_diff_drive.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometrySource>world</odometrySource>
      <publishOdomTF>true</publishOdomTF>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <publishWheelTF>false</publishWheelTF>
      <publishTf>true</publishTf>
      <publishWheelJointState>true</publishWheelJointState>
      <legacyMode>false</legacyMode>
      <updateRate>30</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${track}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <wheelAcceleration>5</wheelAcceleration>
      <wheelTorque>20</wheelTorque>
      <rosDebugLevel>na</rosDebugLevel>
    </plugin>
  </gazebo>
  
<!-- battery plugin for rmf -->
  <gazebo>
    <plugin name="battery_plugin" filename="libgazebo_ros_battery.so">
      <battery_topic>/$(arg botname)_node/$(arg botname)/battery_state</battery_topic>
      <consumer_topic>/$(arg botname)/consumer</consumer_topic>
      <use_nonlinear_model>True</use_nonlinear_model>
      <update_rate>10.0</update_rate>
      <rosDebugLevel>Debug</rosDebugLevel>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>imu_link</bodyName>
      <frameName>imu_link</frameName>
      <topicName>imu</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>200</updateRate>
      <imu>
        <noise>
          <type>gaussian</type>
          <rate>
            <mean>0.0</mean>
            <stddev>2e-4</stddev>
            <bias_mean>0.0000075</bias_mean>
            <bias_stddev>0.0000008</bias_stddev>
          </rate>
          <accel>
            <mean>0.0</mean>
            <stddev>1.7e-2</stddev>
            <bias_mean>0.1</bias_mean>
            <bias_stddev>0.001</bias_stddev>
          </accel>
        </noise>
      </imu>
    </plugin>
  </gazebo>

  <gazebo reference="hokuyo_laser_scanner_1">
    <sensor type="ray" name="front_hokuyo_sensor">
      <!-- <pose>0 0 0 0 0 0</pose> -->
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>1080</samples>
            <resolution>0.25</resolution>
            <min_angle>-2.356</min_angle>
            <max_angle>2.356</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>12</max>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_front_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>front_right/scan</topicName>
        <frameName>hokuyo_laser_scanner_1</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo reference="hokuyo_laser_scanner_2">
    <sensor type="ray" name="back_hokuyo_sensor">
      <!-- <pose>0 0 0 0 0 0</pose> -->
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>1080</samples>
            <resolution>0.25</resolution>
            <min_angle>-2.356</min_angle>
            <max_angle>2.356</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>12</max>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_back_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>back_left/scan</topicName>
        <frameName>hokuyo_laser_scanner_2</frameName>
      </plugin>
    </sensor>
  </gazebo>
</robot>
